musicdb/bp_main/routes.py
import math
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask import render_template
from flask_login import current_user
import werkzeug
from musicdb.bp_artists.routes import parse_artist_url
from musicdb import db, app
from musicdb.bp_utils.func import sec_to_str
from musicdb.general import p_err

from musicdb.models import Artist, Song

bp_main = Blueprint('main', __name__)

############################################################
# ROUTE :: FRONT PAGE
# STATUS :: GOOD ENOUGH
############################################################
@bp_main.route("/")
@bp_main.route("/front")
@bp_main.route("/home") # Legacy / should be replaced by '/front' in future.
def front_page() -> str:
    """
    Route for front page.
    """

    # GENERAL :: page title
    title = 'MusicDB :: front page'

    # Pagination for 'latest uploaded songs'
    # Gets the first page of all uploaded songs, ordered by date, and get only the first 3 (on page 1)
    page = request.args.get('page', 1, type=int)
    entries_per_page = 3


    # A class that acts as a container to hold info over a song (single object = single song)
    class Song_info_container():
        # General
        id = None
        title = None
        album = None
        artist = None
        length = None
        favorite = False # TODO Not implemented yet
        is_owner = False # TODO Not implemented yet

        # CDN
        # (These are 'links' the browser can interpret to get files likes images, the mp3s and suchs)
        cdn_song_icon = None
        cdn_song_file = None

        # URLs
        # Links to other pages that relate to this song
        url_to_song = None
        url_to_album = None
        url_to_artist = None


    # Holds all the song objects in an list that will be able to be looped over with Flask render_template.
    songs_for_display = []

    # From the database; get the last three songs uploaded by datetime.
    songs_retrieved_from_database = Song.query.filter_by().order_by(Song.created_at.desc()).paginate(page=page, per_page=entries_per_page)

    # The reason why we don't directly pass the song objects retrieved from the database to Flask render_template is because some information is missing. Also URL's for CDN and redirecting is easier handeld in Python then in-html Flask {{....}}. We get lacking formation below. Then finally add it the the list (songs_for_display) we made earlier.
    for song in songs_retrieved_from_database:

        song_container = Song_info_container()

        #GENERAL
        song_container.id = song.id
        song_container.title = song.title
        
        # Check if the songs has a connected album. (Some songs aren't part of an album)
        if song.album is not None:
            song_container.album = song.album.name
        else:
            song_container.album = "Unknown album"
            
        # Check if an artist is known for the song. (This could be missing)
        if song.artist is not None:
            song_container.artist = song.artist.name
        else:
            song_container.artist = "Unknown artist"
            
        #  Get the length in seconds of a song.
        song_container.length = sec_to_str(song.length_in_sec)

        # Check if song is favorited by the current user
        # Check in table 'UsersLikesSongs' if the combination of song & current user exists
        # TODO implement favs
        song_container.is_favorite = False

        # CDN
        # Uses from the utils blueprint the CDN functions to determine the relative paths of files.
        if song.file_cover:
            song_container.cdn_song_icon = url_for('utils.cdn_song_icons', filename=song.file_cover)
        if song.file_name:
            song_container.cdn_song_file = url_for('utils.cdn_songs', filename=song.file_name)
            
            
        # URLs
        # TODO use url_for instead of f-strings
        # URL to song
        song_container.url_to_song = f'/song/{song.id}'
        
        # URL to album (if part of album)
        if song.album_id:
            song_container.url_to_album = f'/album/{song.album_id}'
        else:
            song_container.url_to_album = None
        # URL to artist (if artist info exists)
        if song.artist_id:
            song_container.url_to_artist = f'/artist/{song.artist_id}'
        else:
            song_container.url_to_album = None

        
        # Add the song container to the list of songs that will be displayed on the rendered page.
        songs_for_display.append(song_container)

    return render_template('home.html', title=title, songs=songs_for_display)

musicdb/bp_songs/routes.py
import math
from sqlalchemy import func, text, or_
from werkzeug.utils import secure_filename
from musicdb.bp_albums.routes import create_album
from musicdb.bp_artists.routes import create_artist, parse_artist_url
from musicdb.bp_utils.func import sec_to_str
from musicdb.models import Album, Artist, Song, UsersLikesSongs
from .func import generate_song_list

from flask_login import current_user
from musicdb import app, db
from musicdb.general import p_err, p_note
from flask import Blueprint, abort, flash, redirect, render_template, request, url_for
from .forms import UpdateSong, UploadForm
from PIL import Image
import hashlib
import eyed3
import uuid
import os

bp_songs = Blueprint('songs', __name__, template_folder='templates')

############################################################
# Route for uploading songs
# TODO BASICS, rewrite, split responsibilities
############################################################
@bp_songs.route('/upload', methods=['GET', 'POST'])
def upload():

    if not current_user.is_authenticated:
        flash('Please login to start using this part of the website...')
        return redirect(url_for('users.login'))
    
    form = UploadForm()
    if form.validate_on_submit():

        upload_session = upload_songs(form.files.data)
        return redirect( f"{url_for('songs.upload_session', session_id=upload_session)}")

    return render_template('upload.html', form=form)


############################################################
# Route for uploading songs
# Can get files from anyway and fill return upload session
# if any files got uploaded succesfull.
# TODO BASICS, rewrite, split responsibilities
############################################################
def upload_songs(files) -> int:

    # Songs that got succesfully uploaded
    uploaded_files = []
    created_albums = {} # name : album.id

    # Songs that get uploaded belong to an upload session, so later we can edit these songs together.
    upload_session_uuid = uuid.uuid4().int>>32
    upload_session_uuid = str(upload_session_uuid).zfill(32)

    for f in files:
        # To make sure all our filenames are unique, we prefix all files with a short UUID
        song_uuid = uuid.uuid4().int>>32
        song_uuid = str(song_uuid)
        song_uuid = song_uuid[:8].zfill(8)

        secure_file_name = secure_filename(f.filename)

        # Should only be .mp3 right now
        try:
            extension = secure_file_name.split('.').pop().lower()
            if extension.lower() != 'mp3':
                flash("Cannot upload files that are not ''mp3'")
                continue
        except Exception as e:
            continue
        
        filename_with_uuid = f"[{song_uuid}]_{secure_file_name}"
        path_and_file = os.path.join(app.config['TEMP_FOLDER'], filename_with_uuid)
        f.save(path_and_file)
        uploaded_files.append(filename_with_uuid)

        meta_title = 'unknown song'
        meta_artist = None
        meta_album = None
        file_cover = None
        meta_duration_in_sec = -1


        try: 
            meta_file = eyed3.load(path_and_file)
            if meta_file.tag is None:
                raise Exception("No tag was found to retrieve metadata")
            if meta_file.tag:
                p_err('BEEP BOOP')
                meta_title = meta_file.tag.title
                p_err('Tried to get artist meta')
                meta_artist = meta_file.tag.artist
                meta_album = meta_file.tag.album

            if meta_file.info is None:
                raise(Exception('No info was found for this file. Is it broken?'))
            meta_duration_in_sec = meta_file.info.time_secs
    
        except Exception as e:
            print(f"Failed opening file with eye3d: {e}")

                        
        meta_image = None
        for image in meta_file.tag.images:
            # Check if image already exists, else we store it
            image_md5 = hashlib.md5(image.image_data).hexdigest()
            path_for_image = os.path.join(os.path.join(app.config['DATA_FOLDER'], 'songs_covers', f'{image_md5}.png'))
            path_for_icon = os.path.join(os.path.join(app.config['DATA_FOLDER'], 'songs_covers_icon', f'{image_md5}.png'))
            if os.path.isfile(path_for_image):
                print('File already exits! No reason to store again!')
            else:
                image_file = open(path_for_image, 'wb')
                image_file.write(image.image_data)
                image_file.close()

                # Make thumbnail
                image_to_resize = Image.open(path_for_image)
                icon = image_to_resize.resize((128, 128))
                icon.save(path_for_icon)
            # Just support one cover for now
            file_cover = f"{image_md5}.png"
            break

        artist_object = None

        # Check if artist exist, if so. Get the id
        # If not exist, create the artist!
        if meta_artist is None:
            temp = None
            pass
        else:
            artist = None
            artist = Artist.query.filter(func.lower(Artist.name) == func.lower(meta_artist)).first()
            print(f'QUERY RESULT: {artist}')

            if artist:
                artist_object = artist
            else:
                artist_object = create_artist(meta_artist)
            # We are gonna create the artist!
        
        # Make albums
        
        if meta_album is None:
            meta_album_id = None
        else:
            if meta_album in created_albums:
                meta_album_id = created_albums[meta_album]
            else:
                # Create a new album
                meta_album_id = create_album(name=meta_album, album_artist=artist_object, album_cover_copy=file_cover)
                created_albums[meta_album] = meta_album_id


        p_note(f'Meta album id: {meta_album_id}')
        # Add query to DB
        song = Song(title=meta_title,
                    # artist=None, # THIS LITTLE FUCKER WAS CAUSING THE OTHER ARTIST_ID TO OVERRIDE
                    # album=None, # ALMOST FELL FOR THIS SHIT TWICE
                    length_in_sec=meta_duration_in_sec,
                    extension=extension,
                    file_name=filename_with_uuid,
                    user_id=current_user.id,
                    artist=artist_object,
                    album_id=meta_album_id,
                    file_cover=file_cover,
                    upload_session=upload_session_uuid
                    )
        
        
        p_note(f'THIS AFTER{song.artist_id}')
            
        db.session.add(song)

        # Commit db info once all files are uploaded and images are generated succesfully. 
        db.session.commit()

        p_err(song.artist_id)
        p_err(song.user_id)

        # Now move files to persistent folder and mark files as moved succesfull
        
            
    for file in uploaded_files:
        try:
            temp = os.path.join(os.path.join(app.config['DATA_FOLDER'], 'temp', file))
            files = os.path.join(os.path.join(app.config['DATA_FOLDER'], 'songs', file))
            os.rename(temp, files)

            # Mark file stored safely
            db.session.query(Song). \
            filter(Song.file_name == file). \
            update({'moved_to_songs': True})
            db.session.commit()
        except Exception as e:
            # If file moving didn't work, mark files 'dead'
            db.session.query(Song). \
            filter(Song.file_name == file). \
            update({'alive': False})
            db.session.commit()
            flash(f"Failed to upload file {file} Trace: {e}")

    return upload_session_uuid

############################################################
# Route for seeing songs
# Can get files from anyway and fill return upload session
# if any files got uploaded succesfull.
# TODO BASICS, rewrite, split responsibilities
############################################################
@bp_songs.route('/songs', methods=['GET', 'POST'])
def songs():
    
    # GENERAL :: page title
    title = 'MusicDB :: Song list'
    # GENERAL :: Current page
    current_page = request.url
    
    # Pagination settings
    page = request.args.get('page', 1, type=int)
    entries_per_page = 10

    # Cannot show page if visitor is logged in.
    if not current_user.is_authenticated:
        flash('Please login to start using this functionality.')
        return redirect(url_for('users.login'))
    
    # Get songs to display for this page.
    # Also use filter to filter out which songs (for example liked songs, or certain name)
    songs_retrieved_from_database = Song.query.filter(Song.alive==True).paginate(page=page, per_page=entries_per_page)

    # Code reuse for generating song_list.
    songs, paginate = generate_song_list(page=page, entries_per_page=entries_per_page, songs_retrieved_from_database=songs_retrieved_from_database, current_page=current_page)

    return render_template('songs.html', title=title, songs=songs, paginate=paginate)

############################################################
# REDIRECT :: Like song by user
############################################################
@bp_songs.route("/song/<song_id>/like", methods=['GET','POST'])
def action_like_song(song_id):
    current_page = request.args.get('current_page', None)
    like = UsersLikesSongs()
    like.user_id = int(current_user.id)
    like.song_id = int(song_id)
    db.session.add(like)
    db.session.commit()
    return redirect(current_page)

############################################################
# REDIRECT :: Unlike song by user
############################################################
@bp_songs.route("/song/<song_id>/unlike", methods=['GET','POST'])
def action_unlike_song(song_id):
    current_page = request.args.get('current_page', None)
    response = UsersLikesSongs.query.filter_by(user_id=current_user.id, song_id=song_id).all()
    for r in response:

musicdb/bp_utils/routes.py
# STATIC DATA :: SONGS ICONS
# CDN path is what user sees in browser!
from flask import Blueprint, send_from_directory
from musicdb import app

bp_utils = Blueprint('utils', __name__)


@bp_utils.route('/cdn/i/<path:filename>')
def cdn_song_icons(filename):
    return send_from_directory(app.config['SONG_COVERS_ICON'], filename)

@bp_utils.route('/cdn/ib/<path:filename>')
def cdn_song_big(filename):
    return send_from_directory(app.config['SONG_COVER'], filename)

# STATIC DATA :: SONGS
# CDN path is what user sees in browser!
@bp_utils.route('/cdn/s/<path:filename>')
def cdn_songs(filename):
    return send_from_directory(app.config['SONG_FOLDER'], filename)

# STATIC DATA :: SONGS
# CDN path is what user sees in browser!
@bp_utils.route('/cdn/pp/<path:filename>')
def cdn_profile_picture(filename):
    return send_from_directory(app.config['PROFILE_PICTURE'], filename)

# STATIC DATA :: SONGS
# CDN path is what user sees in browser!
@bp_utils.route('/cdn/ac/<path:filename>')
def cdn_band_picture(filename):
    return send_from_directory(app.config['BAND_COVER'], filename)


# STATIC DATA :: SONGS
# CDN path is what user sees in browser!
@bp_utils.route('/cdn/st/<path:long_country_name>')
def cdn_flags(long_country_name):
    country_icon_list = {
        'Netherlands': 'nl',
        'Germany': 'de',
        'United Kingdom': 'gb',
        'Sweden': 'se',
        'Poland': 'pl',
        'Belgium': 'be',
        'USA': 'us',
        'France': 'fr',
        'world': 'xx',
        'Other': None
    }

    return send_from_directory(app.static_folder, f'flags/{country_icon_list[long_country_name]}.svg')


# STATIC DATA :: SONGS
# CDN path is what user sees in browser!
@bp_utils.route('/cdn/sn/<path:filename>')
def cdn_album_cover(filename):
    return send_from_directory(app.config['ALBUM_COVER'], filename)

musicdb/templates/album.html
<!-- What to extend, it this case, our base template -->
{% extends "base.html" %}

<!-- Extra markup that goes in <head> -->
{% block head %}
{{ super() }}

<!-- https://css-tricks.com/snippets/css/complete-guide-grid/ -->
<style>
.grid-parent {
    display: grid;
    width: 100%;
    gap: 20px;


    grid-template-columns: 1fr 1fr 1fr 1fr;
    grid-template-rows: 1fr 1fr;
}

.grid-child {
    border-radius: 25px;
    overflow: hidden;
    background-color: rgba(0, 0, 0, 0.6);


    display: inline-block;
    position: relative;
    width: 100%;

}

.grid-dummy {
  margin-top: 150%;
}

.grid-content {
position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  background-color: silver/* show me! */
}

.cover {
    height: 66.6%;
    width: 100%;
    background-color: red;
    overflow: hidden;
}

.cover img {
    width: 100%;
    height: 100%;
    object-fit: cover;
}

</style>
{% endblock %}

<!-- Homepage content -->
{% block content %}
<br>
<br>

<div class="grid-parent">

    <div class="grid-child">
        <div class="grid-dummy">
            <div class="grid-content">
                <div class="cover">
                    <img src="{{ url_for('static', filename='img/cover.png') }}" alt="">
                </div>
                <div class="content-bottom">

                </div>
            </div>
        </div>

    </div>

    <div class="grid-child">
        <div class="grid-dummy">
            <div class="grid-content">

            </div>
        </div>

    </div>

    <div class="grid-child">
        <div class="grid-dummy">
            <div class="grid-content">

            </div>
        </div>

    </div>

    <div class="grid-child">
        <div class="grid-dummy">
            <div class="grid-content">

            </div>
        </div>

    </div>

    <div class="grid-child">
        <div class="grid-dummy">
            <div class="grid-content">

            </div>
        </div>

    </div>

    <div class="grid-child">
        <div class="grid-dummy">
            <div class="grid-content">

            </div>
        </div>

    </div>

    <div class="grid-child">
        <div class="grid-dummy">
            <div class="grid-content">

            </div>
        </div>

    </div>

    <div class="grid-child">
        <div class="grid-dummy">
            <div class="grid-content">

            </div>
        </div>

    </div>

   
</div>


{% endblock %}

musicdb/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% block head %}
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<!-- Check for title -->
	<title>{% if title %} {{ title }} {% else %} MusicDB {% endif %}</title>

	<!-- Custom favicon -->
	<link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">

	<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/css.css') }}">
	<!-- # Open Sans -->

	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">

	
	{% endblock %}
</head>
<body>
	<br>
	<br>

	<div class="container sticky-top">
		<nav class="navbar bg-body-tertiary rounded-5 navbar-expand-lg" data-bs-theme="dark">
			<div class="container">
			<div class="collapse navbar-collapse d-lg-flex" id="navbarsExample11">
					<!-- left -->
					<a class="navbar-brand col-lg-3 me-0" href="{{ url_for('main.front_page') }}" style="height: 38px; padding-top: 0; padding-bottom: 0;">
						<img src="{{ url_for('static', filename='img/musicdb_logo_light.png') }}" alt="" style="max-height: 100%;">
					</a>
					
					<!-- mid -->
					<ul class="navbar-nav col-lg-6 justify-content-lg-center">

						
						

						<li class="nav-item">
							<div class="btn-group">
								<button type="button" class="btn btn-secondary dropdown-toggle rounded-0 rounded-start-pill" data-bs-toggle="dropdown" aria-expanded="false">Explore</button>
								<span class="visually-hidden">Toggle Dropdown</span>
								</button>
								<ul class="dropdown-menu">
								<li><a class="dropdown-item" href="{{ url_for('songs.songs') }}">Songs</a></li>
								<li><a class="dropdown-item" href="{{ url_for('albums.albums') }}">Albums</a></li>
								<li><a class="dropdown-item" href="{{ url_for('artists.artist_list') }}">Artists</a></li>
								<li><a class="dropdown-item" href="#">Profiles</a></li>
								<li><hr class="dropdown-divider"></li>
								<li><a class="dropdown-item" href="{{ url_for('songs.upload') }}">Upload</a></li>
								</ul>
							</div>
						</li>

						<!-- <li class="nav-item">
							<div class="btn-group">
								<button type="button" class="btn btn-secondary dropdown-toggle rounded-0" data-bs-toggle="dropdown" aria-expanded="false">Explore</button>
								<span class="visually-hidden">Toggle Dropdown</span>
								</button>
								<ul class="dropdown-menu">
								<li><a class="dropdown-item" href="#">Songs</a></li>
								<li><a class="dropdown-item" href="#">Albums</a></li>
								<li><a class="dropdown-item" href="#">Artist</a></li>
								<li><hr class="dropdown-divider"></li>
								<li><a class="dropdown-item" href="#">Users</a></li>
								</ul>
							</div>
						</li> -->

						<li class="nav-item">
							<form role="search">
								<input class="form-control rounded-0" id="c-navbar-search" type="search" placeholder="Search" aria-label="Search">
							</form>
						</li>
						<li class="nav-item">
							<button type="button" class="btn btn btn-secondary rounded-end-pill">
								<img src="{{ url_for('static', filename='icons/search.svg') }}" style="position: relative; bottom: 2px; right: 3px; filter: invert(100%);">
							</button>
						</li>
					</ul>`

					



					<!-- right -->
					<ul class=" navbar-nav col-lg-3 justify-content-lg-end">
						<!-- <li class="nav-item" style="padding-right: 10px;">
							<button type="button" class="btn btn-success rounded-pill">
								<img src="bootstrap-icons-1.11.3/gear-fill.svg" alt="">
							</button>
						</li> -->
						{% if current_user.is_authenticated %}
						<!-- What if there us a user logged in -->


						<li>
							<a href="{{ url_for('users.profile') }}">
								<button type="button" class="btn btn-outline-success rounded-0 rounded-start-pill">
									{{ current_user.username }}
								</button>
							</a>
						</li>

						{% if current_user.admin %}
						<li class="nav-item">
							<div class="btn-group">
								<button type="button" class="btn btn-danger dropdown-toggle rounded-0" data-bs-toggle="dropdown" aria-expanded="false">ADMIN TOOLS</button>
								<span class="visually-hidden"></span>
								</button>
								<ul class="dropdown-menu">
								<li><a class="dropdown-item" href="{{ url_for('artists.artist_add') }}">add artist</a></li>
								<li><a class="dropdown-item" href="#">F.A.Q.</a></li>
								</ul>
							</div>
						</li>
						{% endif %}

						<li class="nav-item">
							<div class="btn-group">
								<button type="button" class="btn btn-success dropdown-toggle rounded-0 rounded-end-pill" data-bs-toggle="dropdown" aria-expanded="false">
									{% if current_user.profile_picture == 'default.jpg' %}
									<img src="{{ url_for('static', filename='img/default_user.jpg') }}" alt="profile picture" class="rounded-5" style="height: 20px; width: 20px; transform: scale(130%);">
									{% else %}
									<img src="{{ url_for('utils.cdn_profile_picture', filename=current_user.profile_picture) }}" alt="profile picture" class="rounded-5" style="height: 20px; width: 20px; transform: scale(130%);">
									{% endif %}
								</button>
								<span class="visually-hidden">Toggle Dropdown</span>
								</button>
								<ul class="dropdown-menu">
								<li><a class="dropdown-item" href="https://github.com/williehaarbal/hanze-flask-songdb">Github</a></li>
								<li><a class="dropdown-item" href="{{ url_for('songs.likes') }}">Likes</a></li>
								<li><hr class="dropdown-divider"></li>
								<li><a class="dropdown-item" href="#">Profile</a></li>
								<li><a class="dropdown-item" href="{{ url_for('users.account') }}">Account</a></li>
								<li><hr class="dropdown-divider"></li>
								<li><a class="dropdown-item" href="{{ url_for('users.logout')}}">Logout</a></li>
								</ul>
							</div>
						</li>

						{% else %}
						<!-- No user logged in -->
						<li class="nav-item">
							<a href="{{ url_for('users.register') }}">
								<button type="button" class="btn btn-success rounded-start-pill">SIGN UP</button>
							</a>
						</li>
						<li class="nav-item">
							<a href="{{ url_for('users.login') }}">
								<button type="button" class="btn btn btn-outline-success rounded-end-pill">SIGN IN</button>
							</a>
						</li>

						{% endif %}
					</ul>
				</div>
			</div>
		</nav>
	</div>


		<div class="container">
			{% block content %}


			{% endblock %}
		</div>

	<!-- Flash messages on bottom of page -->
	{% with messages = get_flashed_messages() %}
	{% if messages %}
	<div class="position-absolute bottom-0 start-50 translate-middle">
		<div class="cointainer">

			{% for message in messages %}
			<div class="alert alert-warning alert-dismissible fade show" role="alert">
				{{ message }}
				<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
			</div>
			{% endfor %}
		</div>
	</div>
	{% endif %}
	{% endwith %}

	<script src="{{ url_for('static', filename='js/bootstrap.bundle.js') }}"></script>
</body>
</html>

musicdb/templates/create_artist.html
<!-- What to extend, it this case, our base template -->
{% extends "base.html" %}

<!-- Extra markup that goes in <head> -->
{% block head %}
  {{ super() }}
<style>
.mid {
    background-color: rgba(0, 0, 0, 0.4);
    border-radius: 25px;
    overflow: hidden;
}


.custom-form-label {
    color: rgba(255, 255, 255, 1);
    padding: 15px 5px 5px 30px;
    font-family: 'Open Sans', sans-serif;
    font-size: 1.2rem;
}

.custom-error-label {
    background-color: white;
    color: red;
    padding: 2px;
    padding-left: 5px;
    margin: 10px 30px 2px 30px;
    border: 2px solid red;
    border-radius: 10px;
    overflow: hidden;
    width: 70%;
}


</style>
{% endblock %}

<!-- Homepage content -->
{% block content %}

<br>
<h1 style="text-align: center; font-family: 'Open Sans', sans-serif; font-weight: 600; font-size: 3.0rem;">Add Artist</h1>

<div class="row">
    <div class="col col-3"></div>
    <div class="col col-6 mid">
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <div class="form-group">
                    {{ form.name.label(class="form-control-label custom-form-label" ) }}

                    {% if form.name.errors %}
                    {{ form.name(class="form-control form-control-lg rounded-5 is-invalid ")}}
                    <div class="invalid-feedback custom-error-label">
                        {% for error in form.name.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                    {% else %}
                        {{ form.name(class="form-control form-control-lg rounded-5")}}
                    {% endif %}
                </div>


                <div class="form-group">
                    {{ form.country_flag.label(class="form-control-label custom-form-label" ) }}
                    {{ form.country_flag(class="form-control form-control-lg rounded-5") }}
                </div>
                <div class="form-group">
                    {{ form.picture.label(class="form-control-label custom-form-label") }}
                    {{ form.picture(class="form-control form-control-lg rounded-5") }}
                </div>
                <div class="form-group">
                    {{ form.description.label(class="form-control-label custom-form-label") }}
                    {{ form.description(class="form-control form-control-lg rounded-5", **{"oninput":"auto_grow(this)"}) }}
                </div>
            </fieldset>
            <div class="submit-button">
                {{ form.submit(class="btn btn-success") }}
            </div>
        </form>
    </div>
    <div class="col col-3"></div>
</div>





<script>
    function auto_grow(element) {
    element.style.height = "5px";
    element.style.height = (element.scrollHeight) + "px";
}
</script>
{% endblock %}

musicdb/templates/home copy.html
<!-- What to extend, it this case, our base template -->
{% extends "base.html" %}

<!-- Extra markup that goes in <head> -->
{% block head %}
  {{ super() }}
  <style type="text/css">
    .important { color: #336699; }
  </style>
{% endblock %}

<!-- Homepage content -->
{% block content %}

<h1>Frontpage</h1>
{{ current_user }}

{% endblock %}